import { Product, Testimonial } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Midnight Oud',
    brand: 'Noir Essence',
    price: 185,
    description: 'A mysterious and captivating blend of rare agarwood, smoked spices, and a touch of midnight jasmine. Perfect for evening wear.',
    notes: ['Oud', 'Smoked Spices', 'Jasmine', 'Leather'],
    image: 'https://picsum.photos/400/600?random=1',
    category: 'Unisex',
    isNew: true,
  },
  {
    id: '2',
    name: 'Velvet Rose',
    brand: 'Noir Essence',
    price: 145,
    description: 'Soft petals of Bulgarian rose resting on a bed of creamy sandalwood and white musk. An elegant, timeless floral.',
    notes: ['Bulgarian Rose', 'Sandalwood', 'White Musk', 'Peony'],
    image: 'https://picsum.photos/400/600?random=2',
    category: 'Women',
  },
  {
    id: '3',
    name: 'Oceanic Drift',
    brand: 'Noir Essence',
    price: 160,
    description: 'The essence of the deep sea. Salty accords mixed with driftwood and citrus zest for a refreshing, masculine edge.',
    notes: ['Sea Salt', 'Driftwood', 'Bergamot', 'Ambroxan'],
    image: 'https://picsum.photos/400/600?random=3',
    category: 'Men',
  },
  {
    id: '4',
    name: 'Amber Haze',
    brand: 'Noir Essence',
    price: 210,
    description: 'Warm, golden amber enveloping a heart of vanilla bean and tobacco leaf. A cozy yet sophisticated scent for winter.',
    notes: ['Amber', 'Vanilla', 'Tobacco', 'Tonka Bean'],
    image: 'https://picsum.photos/400/600?random=4',
    category: 'Unisex',
  },
  {
    id: '5',
    name: 'Citrus Vetiver',
    brand: 'Noir Essence',
    price: 130,
    description: 'Bright italian lemon meets the earthy depth of haitian vetiver. A clean, sharp fragrance for the modern professional.',
    notes: ['Lemon', 'Vetiver', 'Cedar', 'Neroli'],
    image: 'https://picsum.photos/400/600?random=5',
    category: 'Men',
  },
  {
    id: '6',
    name: 'Dark Cherry',
    brand: 'Noir Essence',
    price: 195,
    description: 'Intoxicating black cherry liquer dipped in bitter almond and turkish rose. Seductive and bold.',
    notes: ['Black Cherry', 'Almond', 'Rose Absolute', 'Tonka'],
    image: 'https://picsum.photos/400/600?random=6',
    category: 'Women',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    name: 'Elena Vance',
    role: 'Fashion Editor',
    content: 'Midnight Oud has become my signature scent. It lasts all day and draws compliments wherever I go. Truly a masterpiece of olfactory art.',
    rating: 5,
    avatar: 'https://picsum.photos/100/100?random=10',
  },
  {
    id: 't2',
    name: 'Marcus Thorne',
    role: 'Architect',
    content: 'The minimalist packaging perfectly complements the complex, layered scents. Oceanic Drift is my daily driver.',
    rating: 5,
    avatar: 'https://picsum.photos/100/100?random=11',
  },
  {
    id: 't3',
    name: 'Sophia Li',
    role: 'Sommelier',
    content: 'I appreciate the balance of notes in Velvet Rose. It is not too sweet, not too heavy. Just pure elegance in a bottle.',
    rating: 4,
    avatar: 'https://picsum.photos/100/100?random=12',
  },
];
